logging:
  level:
    org:
      zalando:
        logbook: TRACE
      springframework:
        web:
          servlet:
            DispatcherServlet: debug
    web: info
    ru.neoflex.statement.feign: debug

deal:
  url: 'http://localhost:8082/deal'