name: CI Pipeline

on:
  push:
    branches:
      - develop
      - main
      - 'feature/**'
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: ['calculator', 'deal', 'statement', 'dossier', 'gateway']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/${{ matrix.module }/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build module with Maven
        run: mvn -B -f ${{ matrix.module }}/pom.xml clean package

      - name: Run tests and generate coverage report
        if: ${{ matrix.module != 'dossier' && matrix.module != 'gateway' }}
        run: mvn -B -f ${{ matrix.module }}/pom.xml test jacoco:report

      - name: Upload coverage to Codecov
        if: ${{ matrix.module != 'dossier' && matrix.module != 'gateway' }}
        uses: codecov/codecov-action@v3
        with:
          files: ${{ matrix.module }}/target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}





